<a href="https://colab.research.google.com/github/Anne-va/Numerical-Methods/blob/main/Python_Exercise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Matrix and Its Operations**

$$
A = \begin{bmatrix} -5, 0\\ 4, 1\end{bmatrix},
B = \begin{bmatrix} 6, -3\\ 2, 3\end{bmatrix}\\ $$

In [ ]:
import numpy as np

A = np.array([[-5, 0],
             [4, 1]])
B = np.array([[6, -3],
             [2, 3]])

sum = A + B
difference1 = B - A
difference2 = A - B

In [2]:
print(sum)

[[ 1 -3]
 [ 6  4]]


In [3]:
print(difference1)

[[11 -3]
 [-2  2]]


In [4]:
print(difference2)

[[-11   3]
 [  2  -2]]
