<a href="https://colab.research.google.com/github/Anne-va/Numerical-Methods/blob/main/Python_Exercise_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np 

In [6]:
P = np.array ([[2, 4, -6], [3, -6, 9], [-3, 2, 2]])
print (P)

[[ 2  4 -6]
 [ 3 -6  9]
 [-3  2  2]]


In [7]:
print(int(np.linalg.det(P)))

-119


In [8]:
print(round(np.linalg.det(P)))

-120
